version: 2

jobs:
  build:
    docker:
    - image: circleci/node:8
      environment:
        NPM_CONFIG_PREFIX: "~/.npm-global"

    working_directory: ~/repo

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v2-dependencies-{{ checksum "package-lock.json" }}
    - run:
        name: Set up global NPM
        command: mkdir ~/.npm-global

    - run:
        name: install npm 6.4.0
        command: sudo npm -g install npm@6.4.0

    - run:
        name: Install Dependencies
        command: npm install

    - save_cache:
        paths:
        - node_modules
        key: v2-dependencies-{{ checksum "package-lock.json" }}

    #- run:
    #    name: Lint
    #    command: npm run lint

    # run tests!
    - run: mkdir junit
    - run:
        name: prepare test git user
        command: git config --global user.email "you@example.com" && git config --global user.name "CircleCi Build"
    - run:
        name: Running Tests
        command: npx mocha --reporter mocha-junit-reporter
        environment:
          MOCHA_FILE: junit/test-results.xml
        when: always


    # get code coverage
    #- run:
    #    name: Getting Code Coverage
    #    command: npx istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec && npx codecov
    #    environment:
    #      MOCHA_FILE: junit/test-results.xml
    #    when: always

    - store_test_results:
        path: junit

    - store_artifacts:
        path: junit


workflows:
  version: 2
  build:
    jobs:
    # run build on any branch
    - build
